baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Makoto Saito | 齋藤 真"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "CV"
    url = "/CV/"    

    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "CV"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "Publications"
    url = "/Publications/"    

    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Publications"

    # Weights are used to determine the ordering
    weight = 1
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/msBRF65"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "twitter"
    url = "https://twitter.com/msBRF65"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='twitter'></span>"

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.jpg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-m"

  # Description to display on homepage
  description = "M.E. student at the University of Tokyo."

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  #  showPostsOnHomePage = "popular"

  # Footer text
  footer = "The Marauders"
