version: "3"
services:
  hugo: 
    build:
      args:
        - BASE_IMAGE=klakegg/hugo:0.101.0-ubuntu
      context: .
      dockerfile: Dockerfile
    volumes:
      - "..:/src"
    entrypoint: bash
    ports:
      - "1313:1313"
    tty: true
    working_dir: /src

